server:
  port: 8081

spring:
  application:
    name: movie-info
  profiles:
    active: default
  cloud:
    config:
      enabled: true
      uri: http://configserver:8888
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 5000
        multiplier: 1.5

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://discovery:8761/eureka